services:
    expression.builder:
        class: Vain\Expression\Builder\ExpressionBuilder
        arguments: ['@expression.factory']
    expression.factory:
        class: Vain\Expression\Factory\ExpressionFactory
        arguments: ['@expression.boolean.result.factory']
    expression.boolean.result.factory:
        class: Vain\Expression\Boolean\Result\Factory\BooleanResultFactory